/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as CliRouteRouteImport } from './routes/cli/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsChar123slugChar125DotmdRouteImport } from './routes/posts/{$slug}[.]md'
import { Route as PostsIdRouteImport } from './routes/posts/$id'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiCliProxyRouteImport } from './routes/api/cli-proxy'
import { Route as ApiAgentXRouteImport } from './routes/api/agent/$x'

const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRouteRoute = CliRouteRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PostsChar123slugChar125DotmdRoute =
  PostsChar123slugChar125DotmdRouteImport.update({
    id: '/{$slug}.md',
    path: '/{$slug}.md',
    getParentRoute: () => PostsRouteRoute,
  } as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostsRouteRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliProxyRoute = ApiCliProxyRouteImport.update({
  id: '/api/cli-proxy',
  path: '/api/cli-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentXRoute = ApiAgentXRouteImport.update({
  id: '/api/agent/$x',
  path: '/api/agent/$x',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli': typeof CliRouteRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/api/cli-proxy': typeof ApiCliProxyRoute
  '/api/ping': typeof ApiPingRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/{$slug}.md': typeof PostsChar123slugChar125DotmdRoute
  '/posts/': typeof PostsIndexRoute
  '/api/agent/$x': typeof ApiAgentXRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli': typeof CliRouteRoute
  '/api/cli-proxy': typeof ApiCliProxyRoute
  '/api/ping': typeof ApiPingRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/{$slug}.md': typeof PostsChar123slugChar125DotmdRoute
  '/posts': typeof PostsIndexRoute
  '/api/agent/$x': typeof ApiAgentXRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli': typeof CliRouteRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/api/cli-proxy': typeof ApiCliProxyRoute
  '/api/ping': typeof ApiPingRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/{$slug}.md': typeof PostsChar123slugChar125DotmdRoute
  '/posts/': typeof PostsIndexRoute
  '/api/agent/$x': typeof ApiAgentXRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli'
    | '/posts'
    | '/api/cli-proxy'
    | '/api/ping'
    | '/posts/$id'
    | '/posts/{$slug}.md'
    | '/posts/'
    | '/api/agent/$x'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli'
    | '/api/cli-proxy'
    | '/api/ping'
    | '/posts/$id'
    | '/posts/{$slug}.md'
    | '/posts'
    | '/api/agent/$x'
  id:
    | '__root__'
    | '/'
    | '/cli'
    | '/posts'
    | '/api/cli-proxy'
    | '/api/ping'
    | '/posts/$id'
    | '/posts/{$slug}.md'
    | '/posts/'
    | '/api/agent/$x'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliRouteRoute: typeof CliRouteRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  ApiCliProxyRoute: typeof ApiCliProxyRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiAgentXRoute: typeof ApiAgentXRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/{$slug}.md': {
      id: '/posts/{$slug}.md'
      path: '/{$slug}.md'
      fullPath: '/posts/{$slug}.md'
      preLoaderRoute: typeof PostsChar123slugChar125DotmdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli-proxy': {
      id: '/api/cli-proxy'
      path: '/api/cli-proxy'
      fullPath: '/api/cli-proxy'
      preLoaderRoute: typeof ApiCliProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$x': {
      id: '/api/agent/$x'
      path: '/api/agent/$x'
      fullPath: '/api/agent/$x'
      preLoaderRoute: typeof ApiAgentXRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PostsRouteRouteChildren {
  PostsIdRoute: typeof PostsIdRoute
  PostsChar123slugChar125DotmdRoute: typeof PostsChar123slugChar125DotmdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsIdRoute: PostsIdRoute,
  PostsChar123slugChar125DotmdRoute: PostsChar123slugChar125DotmdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliRouteRoute: CliRouteRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  ApiCliProxyRoute: ApiCliProxyRoute,
  ApiPingRoute: ApiPingRoute,
  ApiAgentXRoute: ApiAgentXRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
