name: Check

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true
  WRANGLER_SEND_METRICS: false

jobs:
  check:
    name: 'Lint, Typecheck, Build'
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: '🔑 Checkout'
        uses: actions/checkout@v6

      - name: '🐰 Setup bun'
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile

      - name: 'Build'
        run: bun run build

      - name: Setup Biome
        uses: biomejs/setup-biome@main
        with:
          version: latest
          
      - name: Format & Lint
        run: biome ci .

      - name: 'Typecheck'
        run: bun tsgo --project tsconfig.json --noEmit
